POST  https://localhost:7076/hosts/3ab4576a-005a-4cd6-b31c-73913d59a00a/menus
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYWI0NTc2YS0wMDVhLTRjZDYtYjMxYy03MzkxM2Q1OWEwMGEiLCJnaXZlbl9uYW1lIjoiTWljaGFsIiwiZmFtaWx5X25hbWUiOiJUb215cyIsImp0aSI6ImNmNzJmMTMwLTIyNTktNDk0MC04OTRiLTcwNDY3ODgwZGFmMCIsImV4cCI6MTY3ODAyNjM0NiwiaXNzIjoiTWUiLCJhdWQiOiJNZSA6KSJ9.DOH8LG6iyhLBUluKzX4dzgMxQFfWAuZIPX7bo3aLUyU

{
  "id": "00000000-0000-0000-0000-000000000000",
  "name": "Yummy Menu",
  "description": "desc",
  "averageRating": {
    "value":4.5,
    "numRatings": 1
  },
  "sections": [
    {
      "id": "00000000-0000-0000-0000-000000000000",
      "name": "Appetizers",
      "description": "descsection",
      "menuItems": [
        {
          "id": "00000000-0000-0000-0000-000000000000",
          "name": "burger",
          "description": "tasty burger"
        }
      ]
    }
  ],
  "hostId": "00000000-0000-0000-0000-000000000000",
  "dinnerIds": [
    "00000000-0000-0000-0000-000000000000"
  ],
  "menuReviewIds": [
    "00000000-0000-0000-0000-000000000000"
  ],
  "createdDateTime": "2020-01-01T00:00.0000000Z",
  "updatedDateTime": "2020-01-01T00:00.0000000Z"
}
