GET  https://localhost:7076/dinners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NDY0OTkwYS1iZGQ0LTQzZjUtYTYzYi1kMjFjM2ZjOTVmN2MiLCJnaXZlbl9uYW1lIjoiTWljaGFsIiwiZmFtaWx5X25hbWUiOiJUb215cyIsImp0aSI6IjMwYTdiZmE3LTYzOGMtNGNjOS05ZjY4LTNiOTQ2NjkwOTNiZSIsImV4cCI6MTY3NzAxNDk0MSwiaXNzIjoiTWUiLCJhdWQiOiJNZSA6KSJ9.gLzF6p6RoXbVR__YjKnz5u5uMzZo0iXM5h6pSgEahoo
